import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#f4f8ff" },
  content: { padding: 20, gap: 16 },
  hero: { padding: 28, gap: 14, flex: 1, justifyContent: "center" },
  brand: { fontSize: 20, fontWeight: "800", color: "#0b4ea2" },
  title: { fontSize: 34, fontWeight: "800", color: "#101828" },
  copy: { fontSize: 16, lineHeight: 24, color: "#475467" },
  actions: { padding: 24, gap: 12 },
  icon: { width: 96, height: 96, borderRadius: 22, marginBottom: 8 },
  panel: { backgroundColor: "#ffffff", borderRadius: 8, padding: 16, gap: 12, borderWidth: 1, borderColor: "#d7e7ff" },
  stepPanel: { backgroundColor: "#eaf3ff", borderRadius: 8, padding: 12, borderWidth: 1, borderColor: "#b8d7ff" },
  sectionTitle: { fontSize: 18, fontWeight: "700", color: "#101828" },
  muted: { color: "#475467" },
  field: { gap: 6 },
  label: { color: "#344054", fontWeight: "600" },
  input: { borderWidth: 1, borderColor: "#b8d7ff", borderRadius: 6, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: "#fff" },
  multi: { minHeight: 76, textAlignVertical: "top" },
  camera: { flex: 1 },
  cameraActions: { padding: 20, gap: 12, backgroundColor: "#f4f8ff" },
  evidenceRow: { flexDirection: "row", gap: 12, alignItems: "center", justifyContent: "space-between" },
  evidenceText: { flex: 1, gap: 4 },
  primary: { minHeight: 46, borderRadius: 6, backgroundColor: "#1d63ed", alignItems: "center", justifyContent: "center", paddingHorizontal: 16 },
  primaryText: { color: "#fff", fontWeight: "800" },
  secondary: { minHeight: 46, borderRadius: 6, borderWidth: 1, borderColor: "#1d63ed", alignItems: "center", justifyContent: "center", paddingHorizontal: 16 },
  secondaryText: { color: "#1d63ed", fontWeight: "800" },
  stepActions: { flexDirection: "row", gap: 10 },
  stepButton: { flex: 1 },
  message: { color: "#0b4ea2", fontWeight: "600" },
  success: { color: "#0b4ea2", fontWeight: "700", lineHeight: 20 }
});
