services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ../keycloak/finflow-local-realm.json:/opt/keycloak/data/import/finflow-local-realm.json:ro

  user-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: finflow
      POSTGRES_PASSWORD: finflow
    ports:
      - "5433:5432"

  kyc-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: kyc_service
      POSTGRES_USER: finflow
      POSTGRES_PASSWORD: finflow
    ports:
      - "5434:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
